### ISSUE TITLE
Image source/licence

### ISSUE THREAD

**Issue by willfurnell** [Breq16/wallmatrix#4]
Hello,
Your weather images look to be a perfect resolution for a flipdot display that I have. Are these your original work, and if so what are they licensed as, or do you know the original source and their license please? For my personal use only.
Thanks!

**Comment by breqdev** [comment]
I couldn't quite remember where I had gotten them from, but I did some digging and found the originals: https://github.com/Dhole/weather-pixel-icons. I remember re-coloring them myself for this.

It looks like the original source is CC-BY-SA-4.0 (oops! i'll add an attribution statement to the repo right now), so you're free to use these for any commercial or non-commercial use with attribution to the original source.

Best of luck with your flipdot display project -- that sounds cool!

**Comment by willfurnell** [comment]
Thank you very much!
